In [1]:
#Importing packages
import pandas as pd
import numpy as np

In [2]:
# #TO create a DF
# 1.Determine the columns
# 2.Using for loop  and numpy generate some fake values
# 3.Create a empty Dataframe

In [3]:
df=pd.DataFrame(columns=['COlumn1','COlumn2'])

In [4]:
df

Empty DataFrame
Columns: [COlumn1, COlumn2]
Index: []

In [5]:
df['COlumn1']=np.random.choice([1,0],99)

In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
df

COlumn1 COlumn2
0         0     NaN
1         0     NaN
2         0     NaN
3         0     NaN
4         0     NaN
..      ...     ...
94        0     NaN
95        0     NaN
96        0     NaN
97        1     NaN
98        1     NaN

[99 rows x 2 columns]

In [8]:
df.iloc[1,1]=58

In [9]:
df

COlumn1 COlumn2
0         0     NaN
1         0      58
2         0     NaN
3         0     NaN
4         0     NaN
..      ...     ...
94        0     NaN
95        0     NaN
96        0     NaN
97        1     NaN
98        1     NaN

[99 rows x 2 columns]

In [10]:
df.iloc[0,1]=58

In [11]:
df

COlumn1 COlumn2
0         0      58
1         0      58
2         0     NaN
3         0     NaN
4         0     NaN
..      ...     ...
94        0     NaN
95        0     NaN
96        0     NaN
97        1     NaN
98        1     NaN

[99 rows x 2 columns]

In [12]:
dic={'COlumn1':47,'COlumn2':57}

In [13]:
new_df=pd.DataFrame(dic,index=[99])

In [14]:
df=pd.concat([df,new_df])  

In [15]:
df

COlumn1 COlumn2
0         0      58
1         0      58
2         0     NaN
3         0     NaN
4         0     NaN
..      ...     ...
95        0     NaN
96        0     NaN
97        1     NaN
98        1     NaN
99       47      57

[100 rows x 2 columns]

In [16]:
df['COlumn3']=np.arange(1,101,1)

In [17]:
df

COlumn1 COlumn2  COlumn3
0         0      58        1
1         0      58        2
2         0     NaN        3
3         0     NaN        4
4         0     NaN        5
..      ...     ...      ...
95        0     NaN       96
96        0     NaN       97
97        1     NaN       98
98        1     NaN       99
99       47      57      100

[100 rows x 3 columns]

In [18]:
df['COlumn2'].fillna(df['COlumn2'].mean())

0     58.000000
1     58.000000
2     57.666667
3     57.666667
4     57.666667
        ...    
95    57.666667
96    57.666667
97    57.666667
98    57.666667
99    57.000000
Name: COlumn2, Length: 100, dtype: float64

In [19]:
df['COlumn2']=df['COlumn2'].fillna(df['COlumn2'].mean())

In [20]:
df

COlumn1    COlumn2  COlumn3
0         0  58.000000        1
1         0  58.000000        2
2         0  57.666667        3
3         0  57.666667        4
4         0  57.666667        5
..      ...        ...      ...
95        0  57.666667       96
96        0  57.666667       97
97        1  57.666667       98
98        1  57.666667       99
99       47  57.000000      100

[100 rows x 3 columns]

In [21]:
df.isnull()

COlumn1  COlumn2  COlumn3
0     False    False    False
1     False    False    False
2     False    False    False
3     False    False    False
4     False    False    False
..      ...      ...      ...
95    False    False    False
96    False    False    False
97    False    False    False
98    False    False    False
99    False    False    False

[100 rows x 3 columns]

In [22]:
import math
math.floor(df['COlumn2'].mean())

57

In [23]:
df.describe()

COlumn1     COlumn2     COlumn3
count  100.000000  100.000000  100.000000
mean     0.940000   57.666667   50.500000
std      4.679247    0.082061   29.011492
min      0.000000   57.000000    1.000000
25%      0.000000   57.666667   25.750000
50%      0.000000   57.666667   50.500000
75%      1.000000   57.666667   75.250000
max     47.000000   58.000000  100.000000

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   COlumn1  100 non-null    int64  
 1   COlumn2  100 non-null    float64
 2   COlumn3  100 non-null    int32  
dtypes: float64(1), int32(1), int64(1)
memory usage: 2.7 KB


In [25]:
for x in df.index:
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [26]:
df.columns

Index(['COlumn1', 'COlumn2', 'COlumn3'], dtype='object')

In [27]:
df.index

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
            68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
            85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
           dtype='int64')

In [28]:
df['COlumn4']=np.random.choice(['AI&ML','AI&DA','CYS'],100)

In [29]:
a=np.random.choice(['AI&ML','AI&DA','CYS'],100)

In [30]:
a

array(['CYS', 'AI&ML', 'AI&DA', 'AI&ML', 'CYS', 'AI&DA', 'AI&ML', 'AI&DA',
       'CYS', 'AI&ML', 'AI&ML', 'AI&DA', 'AI&DA', 'AI&DA', 'AI&ML',
       'AI&ML', 'AI&DA', 'AI&ML', 'AI&DA', 'CYS', 'AI&DA', 'AI&DA', 'CYS',
       'AI&DA', 'CYS', 'AI&ML', 'CYS', 'AI&DA', 'AI&ML', 'AI&ML', 'AI&ML',
       'AI&DA', 'AI&DA', 'AI&DA', 'AI&ML', 'AI&ML', 'AI&ML', 'CYS',
       'AI&DA', 'AI&ML', 'AI&DA', 'AI&ML', 'AI&DA', 'AI&ML', 'CYS',
       'AI&ML', 'AI&ML', 'CYS', 'AI&ML', 'AI&DA', 'AI&DA', 'AI&ML', 'CYS',
       'AI&DA', 'AI&ML', 'CYS', 'AI&ML', 'AI&DA', 'CYS', 'CYS', 'CYS',
       'AI&ML', 'AI&DA', 'AI&DA', 'CYS', 'AI&DA', 'AI&DA', 'AI&DA', 'CYS',
       'CYS', 'AI&ML', 'AI&DA', 'CYS', 'CYS', 'CYS', 'CYS', 'AI&DA',
       'AI&DA', 'CYS', 'AI&DA', 'AI&DA', 'AI&DA', 'AI&DA', 'AI&DA',
       'AI&DA', 'AI&ML', 'AI&DA', 'AI&ML', 'AI&ML', 'AI&ML', 'AI&ML',
       'CYS', 'AI&DA', 'CYS', 'AI&DA', 'CYS', 'AI&ML', 'AI&ML', 'AI&ML',
       'AI&DA'], dtype='<U5')

In [31]:
df['Column4']=a

In [32]:
df

COlumn1    COlumn2  COlumn3 COlumn4 Column4
0         0  58.000000        1   AI&ML     CYS
1         0  58.000000        2     CYS   AI&ML
2         0  57.666667        3     CYS   AI&DA
3         0  57.666667        4     CYS   AI&ML
4         0  57.666667        5     CYS     CYS
..      ...        ...      ...     ...     ...
95        0  57.666667       96     CYS     CYS
96        0  57.666667       97     CYS   AI&ML
97        1  57.666667       98     CYS   AI&ML
98        1  57.666667       99   AI&DA   AI&ML
99       47  57.000000      100   AI&ML   AI&DA

[100 rows x 5 columns]

In [33]:
df.loc[0,'Column4']="DA"

In [34]:
df

COlumn1    COlumn2  COlumn3 COlumn4 Column4
0         0  58.000000        1   AI&ML      DA
1         0  58.000000        2     CYS   AI&ML
2         0  57.666667        3     CYS   AI&DA
3         0  57.666667        4     CYS   AI&ML
4         0  57.666667        5     CYS     CYS
..      ...        ...      ...     ...     ...
95        0  57.666667       96     CYS     CYS
96        0  57.666667       97     CYS   AI&ML
97        1  57.666667       98     CYS   AI&ML
98        1  57.666667       99   AI&DA   AI&ML
99       47  57.000000      100   AI&ML   AI&DA

[100 rows x 5 columns]

In [35]:
set(df['Column4'])

{'AI&DA', 'AI&ML', 'CYS', 'DA'}

In [36]:
dic={'AI&DA':'Artificial Intelligence & Data Analytics','DA':'Artificial Intelligence & Data Analytics','AI&ML':'Artificial Intelligence & Machine Learning','CYS':'CYber Security'}

In [37]:
df['Column4']=df['Column4'].map(dic)

In [38]:
df

COlumn1    COlumn2  COlumn3 COlumn4  \
0         0  58.000000        1   AI&ML   
1         0  58.000000        2     CYS   
2         0  57.666667        3     CYS   
3         0  57.666667        4     CYS   
4         0  57.666667        5     CYS   
..      ...        ...      ...     ...   
95        0  57.666667       96     CYS   
96        0  57.666667       97     CYS   
97        1  57.666667       98     CYS   
98        1  57.666667       99   AI&DA   
99       47  57.000000      100   AI&ML   

                                       Column4  
0     Artificial Intelligence & Data Analytics  
1   Artificial Intelligence & Machine Learning  
2     Artificial Intelligence & Data Analytics  
3   Artificial Intelligence & Machine Learning  
4                               CYber Security  
..                                         ...  
95                              CYber Security  
96  Artificial Intelligence & Machine Learning  
97  Artificial Intelligence & Machine Learning  
98  Artificial Intelligence & Machine Learning  
99    Artificial Intelligence & Data Analytics  

[100 rows x 5 columns]

In [39]:
del df['COlumn4']

In [40]:
df

COlumn1    COlumn2  COlumn3                                     Column4
0         0  58.000000        1    Artificial Intelligence & Data Analytics
1         0  58.000000        2  Artificial Intelligence & Machine Learning
2         0  57.666667        3    Artificial Intelligence & Data Analytics
3         0  57.666667        4  Artificial Intelligence & Machine Learning
4         0  57.666667        5                              CYber Security
..      ...        ...      ...                                         ...
95        0  57.666667       96                              CYber Security
96        0  57.666667       97  Artificial Intelligence & Machine Learning
97        1  57.666667       98  Artificial Intelligence & Machine Learning
98        1  57.666667       99  Artificial Intelligence & Machine Learning
99       47  57.000000      100    Artificial Intelligence & Data Analytics

[100 rows x 4 columns]

In [41]:
dic={'Artificial Intelligence & Machine Learning':'E01','CYber Security':'E02','Artificial Intelligence & Data Analytics':'E03'}

In [42]:
df['Column5']=df['Column4'].map(dic)

In [43]:
df['Column4']

0       Artificial Intelligence & Data Analytics
1     Artificial Intelligence & Machine Learning
2       Artificial Intelligence & Data Analytics
3     Artificial Intelligence & Machine Learning
4                                 CYber Security
                         ...                    
95                                CYber Security
96    Artificial Intelligence & Machine Learning
97    Artificial Intelligence & Machine Learning
98    Artificial Intelligence & Machine Learning
99      Artificial Intelligence & Data Analytics
Name: Column4, Length: 100, dtype: object

In [44]:
df

COlumn1    COlumn2  COlumn3                                     Column4  \
0         0  58.000000        1    Artificial Intelligence & Data Analytics   
1         0  58.000000        2  Artificial Intelligence & Machine Learning   
2         0  57.666667        3    Artificial Intelligence & Data Analytics   
3         0  57.666667        4  Artificial Intelligence & Machine Learning   
4         0  57.666667        5                              CYber Security   
..      ...        ...      ...                                         ...   
95        0  57.666667       96                              CYber Security   
96        0  57.666667       97  Artificial Intelligence & Machine Learning   
97        1  57.666667       98  Artificial Intelligence & Machine Learning   
98        1  57.666667       99  Artificial Intelligence & Machine Learning   
99       47  57.000000      100    Artificial Intelligence & Data Analytics   

   Column5  
0      E03  
1      E01  
2      E03  
3      E01  
4      E02  
..     ...  
95     E02  
96     E01  
97     E01  
98     E01  
99     E03  

[100 rows x 5 columns]

In [45]:
df=pd.read_clipboard()

In [46]:
df

1  67  1000
0   2  17  1547
1   5  96  2587
2   6  74  4586
3   3  38  3578
4   4  87  1486
5   8  54  5713
6   3  43  9841
7   4  23  2684
8   2  32  7513
9   4  23  9855
10  5  23  4521
11  3  12  1564

In [47]:
df['new1']=df['1']/max(df['1'])

In [48]:
df

1  67  1000   new1
0   2  17  1547  0.250
1   5  96  2587  0.625
2   6  74  4586  0.750
3   3  38  3578  0.375
4   4  87  1486  0.500
5   8  54  5713  1.000
6   3  43  9841  0.375
7   4  23  2684  0.500
8   2  32  7513  0.250
9   4  23  9855  0.500
10  5  23  4521  0.625
11  3  12  1564  0.375

In [55]:
df['new2']=(df['67']-min(df['67']))/(max(df['67'])-min(df['67']))

In [56]:
df

1  67  1000   new1      new2      new3
0   2  17  1547  0.250  0.059524 -1.011055
1   5  96  2587  0.625  1.000000 -0.669207
2   6  74  4586  0.750  0.738095 -0.012135
3   3  38  3578  0.375  0.309524 -0.343465
4   4  87  1486  0.500  0.892857 -1.031106
5   8  54  5713  1.000  0.500000  0.358311
6   3  43  9841  0.375  0.369048  1.715186
7   4  23  2684  0.500  0.130952 -0.637323
8   2  32  7513  0.250  0.238095  0.949972
9   4  23  9855  0.500  0.130952  1.719788
10  5  23  4521  0.625  0.130952 -0.033500
11  3  12  1564  0.375  0.000000 -1.005467

In [57]:
df['new3']=(df['1000']-(df['1000'].mean()))/((df['1000']).std())

In [58]:
df

1  67  1000   new1      new2      new3
0   2  17  1547  0.250  0.059524 -1.011055
1   5  96  2587  0.625  1.000000 -0.669207
2   6  74  4586  0.750  0.738095 -0.012135
3   3  38  3578  0.375  0.309524 -0.343465
4   4  87  1486  0.500  0.892857 -1.031106
5   8  54  5713  1.000  0.500000  0.358311
6   3  43  9841  0.375  0.369048  1.715186
7   4  23  2684  0.500  0.130952 -0.637323
8   2  32  7513  0.250  0.238095  0.949972
9   4  23  9855  0.500  0.130952  1.719788
10  5  23  4521  0.625  0.130952 -0.033500
11  3  12  1564  0.375  0.000000 -1.005467

In [59]:
lst=[1,2,3,4,5,6]
arr=np.array(lst)

In [60]:
arr

array([1, 2, 3, 4, 5, 6])

In [61]:
arr=np.array([1,2,3,4,5,6,7])

In [62]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [63]:
lst[2]

3

In [68]:
arr.shape

(2, 5, 2, 5)

In [66]:
arr=np.arange(0,100).reshape(2,5,2,5)

In [67]:
arr

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]]],


       [[[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]],

        [[60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69]],

        [[70, 71, 72, 73, 74],
         [75, 76, 77, 78, 79]],

        [[80, 81, 82, 83, 84],
         [85, 86, 87, 88, 89]],

        [[90, 91, 92, 93, 94],
         [95, 96, 97, 98, 99]]]])

In [ ]:
2,5,2,5

In [69]:
arr[0]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [70]:
arr.shape

(2, 5, 2, 5)

In [74]:
arr

array([[[[495, 339, 476],
         [371, 409, 334],
         [232, 324, 484],
         [397, 325, 231]],

        [[251, 496, 264],
         [377, 301, 443],
         [388, 434, 271],
         [228, 394, 295]]],


       [[[431, 405, 244],
         [221, 454, 201],
         [241, 311, 464],
         [242, 346, 310]],

        [[254, 247, 466],
         [491, 218, 295],
         [200, 263, 411],
         [377, 310, 417]]],


       [[[376, 213, 352],
         [342, 210, 231],
         [258, 208, 420],
         [463, 304, 259]],

        [[294, 343, 226],
         [441, 464, 437],
         [238, 229, 375],
         [230, 376, 200]]],


       [[[336, 316, 466],
         [464, 464, 432],
         [418, 368, 335],
         [294, 254, 234]],

        [[370, 459, 282],
         [257, 330, 425],
         [268, 416, 202],
         [378, 499, 400]]],


       [[[257, 318, 481],
         [463, 285, 211],
         [290, 458, 490],
         [408, 488, 498]],

        [[235, 355, 254],
         [47

In [ ]:
5,2,4,3

In [77]:
arr.shape

(5, 2, 4, 3)

In [79]:
arr

array([[[[141, 157],
         [141, 568],
         [141, 568],
         [157, 157]],

        [[141, 568],
         [141, 157],
         [141, 141],
         [568, 568]],

        [[157, 141],
         [157, 157],
         [141, 568],
         [141, 568]]],


       [[[568, 568],
         [568, 568],
         [141, 157],
         [157, 141]],

        [[157, 157],
         [141, 141],
         [157, 568],
         [157, 141]],

        [[568, 157],
         [568, 568],
         [157, 568],
         [157, 568]]],


       [[[141, 141],
         [568, 157],
         [568, 568],
         [568, 568]],

        [[141, 141],
         [141, 157],
         [141, 157],
         [141, 568]],

        [[141, 141],
         [157, 141],
         [141, 157],
         [568, 157]]],


       [[[568, 157],
         [141, 568],
         [157, 157],
         [141, 141]],

        [[141, 141],
         [141, 568],
         [568, 141],
         [568, 157]],

        [[568, 568],
         [157, 568],
      

In [80]:
arr.shape

(5, 3, 4, 2)

In [81]:
arr=arr.flatten()

In [82]:
arr

array([141, 157, 141, 568, 141, 568, 157, 157, 141, 568, 141, 157, 141,
       141, 568, 568, 157, 141, 157, 157, 141, 568, 141, 568, 568, 568,
       568, 568, 141, 157, 157, 141, 157, 157, 141, 141, 157, 568, 157,
       141, 568, 157, 568, 568, 157, 568, 157, 568, 141, 141, 568, 157,
       568, 568, 568, 568, 141, 141, 141, 157, 141, 157, 141, 568, 141,
       141, 157, 141, 141, 157, 568, 157, 568, 157, 141, 568, 157, 157,
       141, 141, 141, 141, 141, 568, 568, 141, 568, 157, 568, 568, 157,
       568, 157, 568, 157, 568, 157, 568, 568, 157, 568, 141, 141, 141,
       568, 141, 157, 568, 141, 141, 568, 141, 157, 568, 157, 157, 141,
       141, 568, 157])

In [83]:
arr.shape

(120,)

In [88]:
arr=np.arange(1,1001).reshape(2,50,10)

In [89]:
arr

array([[[   1,    2,    3,    4,    5,    6,    7,    8,    9,   10],
        [  11,   12,   13,   14,   15,   16,   17,   18,   19,   20],
        [  21,   22,   23,   24,   25,   26,   27,   28,   29,   30],
        [  31,   32,   33,   34,   35,   36,   37,   38,   39,   40],
        [  41,   42,   43,   44,   45,   46,   47,   48,   49,   50],
        [  51,   52,   53,   54,   55,   56,   57,   58,   59,   60],
        [  61,   62,   63,   64,   65,   66,   67,   68,   69,   70],
        [  71,   72,   73,   74,   75,   76,   77,   78,   79,   80],
        [  81,   82,   83,   84,   85,   86,   87,   88,   89,   90],
        [  91,   92,   93,   94,   95,   96,   97,   98,   99,  100],
        [ 101,  102,  103,  104,  105,  106,  107,  108,  109,  110],
        [ 111,  112,  113,  114,  115,  116,  117,  118,  119,  120],
        [ 121,  122,  123,  124,  125,  126,  127,  128,  129,  130],
        [ 131,  132,  133,  134,  135,  136,  137,  138,  139,  140],
        [ 141,  142,

In [90]:
arr.ravel()

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [91]:
arr

array([[[   1,    2,    3,    4,    5,    6,    7,    8,    9,   10],
        [  11,   12,   13,   14,   15,   16,   17,   18,   19,   20],
        [  21,   22,   23,   24,   25,   26,   27,   28,   29,   30],
        [  31,   32,   33,   34,   35,   36,   37,   38,   39,   40],
        [  41,   42,   43,   44,   45,   46,   47,   48,   49,   50],
        [  51,   52,   53,   54,   55,   56,   57,   58,   59,   60],
        [  61,   62,   63,   64,   65,   66,   67,   68,   69,   70],
        [  71,   72,   73,   74,   75,   76,   77,   78,   79,   80],
        [  81,   82,   83,   84,   85,   86,   87,   88,   89,   90],
        [  91,   92,   93,   94,   95,   96,   97,   98,   99,  100],
        [ 101,  102,  103,  104,  105,  106,  107,  108,  109,  110],
        [ 111,  112,  113,  114,  115,  116,  117,  118,  119,  120],
        [ 121,  122,  123,  124,  125,  126,  127,  128,  129,  130],
        [ 131,  132,  133,  134,  135,  136,  137,  138,  139,  140],
        [ 141,  142,

In [92]:
arr=np.arange(1,1001).reshape(2,50,10)

In [93]:
arr

array([[[   1,    2,    3,    4,    5,    6,    7,    8,    9,   10],
        [  11,   12,   13,   14,   15,   16,   17,   18,   19,   20],
        [  21,   22,   23,   24,   25,   26,   27,   28,   29,   30],
        [  31,   32,   33,   34,   35,   36,   37,   38,   39,   40],
        [  41,   42,   43,   44,   45,   46,   47,   48,   49,   50],
        [  51,   52,   53,   54,   55,   56,   57,   58,   59,   60],
        [  61,   62,   63,   64,   65,   66,   67,   68,   69,   70],
        [  71,   72,   73,   74,   75,   76,   77,   78,   79,   80],
        [  81,   82,   83,   84,   85,   86,   87,   88,   89,   90],
        [  91,   92,   93,   94,   95,   96,   97,   98,   99,  100],
        [ 101,  102,  103,  104,  105,  106,  107,  108,  109,  110],
        [ 111,  112,  113,  114,  115,  116,  117,  118,  119,  120],
        [ 121,  122,  123,  124,  125,  126,  127,  128,  129,  130],
        [ 131,  132,  133,  134,  135,  136,  137,  138,  139,  140],
        [ 141,  142,

In [94]:
arr.flatten()

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [142]:
arr

array([ 21, -47,  50, -61])

In [114]:
arr=np.arange(1,7)

In [115]:
arr

array([1, 2, 3, 4, 5, 6])

In [116]:
arr1=arr

In [117]:
arr1

array([1, 2, 3, 4, 5, 6])

In [118]:
arr

array([1, 2, 3, 4, 5, 6])

In [122]:
arr1

array([1, 2, 3, 4, 5, 6])

In [121]:
arr

array([2, 3, 4, 5, 6, 7])

In [123]:
np.random.randint(1,10,100)

array([7, 4, 7, 9, 4, 6, 8, 4, 9, 2, 8, 8, 1, 9, 6, 2, 2, 1, 9, 6, 9, 7,
       8, 9, 1, 6, 1, 5, 6, 8, 5, 4, 8, 7, 2, 1, 3, 6, 5, 5, 2, 8, 6, 1,
       2, 1, 4, 5, 2, 3, 1, 5, 7, 8, 5, 5, 8, 2, 7, 6, 6, 1, 8, 7, 7, 2,
       7, 1, 8, 4, 9, 1, 5, 4, 4, 1, 2, 9, 6, 6, 3, 4, 5, 3, 4, 6, 7, 3,
       7, 6, 5, 8, 9, 2, 6, 4, 6, 1, 8, 4])

In [124]:
arr=np.array([1,2,3])

In [125]:
np.random.choice(arr,10)

array([2, 1, 3, 1, 2, 1, 2, 3, 1, 1])

In [127]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [128]:
arr=np.array([77,82,69,1,7])

In [129]:
arr

array([77, 82, 69,  1,  7])

In [130]:
np.argsort(arr)

array([3, 4, 2, 0, 1], dtype=int64)

In [131]:
np.sort(arr)

array([ 1,  7, 69, 77, 82])

In [132]:
arr=np.array([21,-47,50,-61])

In [133]:
arr

array([ 21, -47,  50, -61])

In [134]:
np.argsort(arr)

array([3, 1, 0, 2], dtype=int64)

In [136]:
a=np.array([3,8,5,4,1])
b=np.array([9,1,7,0,5])

In [137]:
a.max()

8

In [138]:
a.min()

1

In [139]:
np.maximum(a,b)

array([9, 8, 7, 4, 5])

In [140]:
np.minimum(a,b)

array([3, 1, 5, 0, 1])

In [141]:
np.ndim(arr)

1

In [173]:
arr=np.arange(1,10).reshape(3,3)

In [174]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [175]:
mat=np.matrix(arr)

In [176]:
mat

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [181]:
np.invert(arr)

array([[ -2,  -3,  -4],
       [ -5,  -6,  -7],
       [ -8,  -9, -10]], dtype=int32)

In [182]:
np.linalg.inv(arr)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [183]:
np.linalg.det(arr)

6.66133814775094e-16

In [184]:
np.linalg.eig(arr)

(array([ 1.61168440e+01, -1.11684397e+00, -4.22209278e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [185]:
np.sum(a)

21

In [186]:
a.sum()

21

In [188]:
arr

array([[[[235, 392, 461, 616, 463, 270, 398],
         [626, 572, 471, 839, 819, 274, 483],
         [929, 583, 981,  81, 483,  51, 507],
         [148, 869, 282, 426, 551, 755, 533],
         [458, 872, 812, 216, 751,  78,  86]],

        [[585, 921, 334, 637, 479, 651, 981],
         [676, 528,  34,  40, 936,  15, 202],
         [960, 913, 346, 216, 889, 352, 722],
         [276, 911, 803, 297, 464, 951,  31],
         [647, 271, 508, 615, 999, 792, 539]],

        [[ 16, 900, 801, 654, 347, 502, 193],
         [735,  26, 292, 870,  94, 470, 620],
         [513, 121, 574, 764, 821, 870, 202],
         [461, 283, 720, 609, 225, 111, 479],
         [572, 760, 693, 163, 942, 426, 210]],

        [[442, 877, 446, 252, 996, 203, 814],
         [788, 698, 190, 216,  47, 151, 960],
         [252, 325, 571,  99, 340, 343, 511],
         [229, 389, 327,  13, 408, 426, 906],
         [973, 977, 902, 884,  67, 464, 837]],

        [[866, 423, 182, 250, 964, 325, 490],
         [740,  36, 886, 6

In [189]:
arr.shape

(2, 5, 5, 7)

ARRAY Operations
        ARRAY INSERTION
        ARRAY APPENDING
        ARRAY DELETION

In [39]:
arr=np.arange(1,41).reshape(5,4,2)
arr

<IPython.core.display.Javascript object>

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30],
        [31, 32]],

       [[33, 34],
        [35, 36],
        [37, 38],
        [39, 40]]])

In [40]:
new_arr=np.array([8.1,8.2,8.3,8.4,8.5,8.6,8.7,8.8]).reshape(4,2)

<IPython.core.display.Javascript object>

In [42]:
np.insert(arr,1,new_arr,axis=0)

<IPython.core.display.Javascript object>

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 8,  8],
        [ 8,  8],
        [ 8,  8],
        [ 8,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30],
        [31, 32]],

       [[33, 34],
        [35, 36],
        [37, 38],
        [39, 40]]])

In [9]:
new_array=np.array([21,22,23,24,25,26,27,28])

<IPython.core.display.Javascript object>

In [16]:
new_array.shape=(4,2)

In [17]:
new_array

array([[21, 22],
       [23, 24],
       [25, 26],
       [27, 28]])

In [20]:
array=np.insert(arr,1,new_array,axis=0)

<IPython.core.display.Javascript object>

In [21]:
array

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30],
        [31, 32]],

       [[33, 34],
        [35, 36],
        [37, 38],
        [39, 40]]])

In [29]:
arr=np.arange(5,25).reshape(5,4)

<IPython.core.display.Javascript object>

In [30]:
arr

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [33]:
new_arr=np.array([25,26,27,28])

<IPython.core.display.Javascript object>

In [36]:
new_array=np.insert(arr,2,new_arr,axis=0)

<IPython.core.display.Javascript object>

In [37]:
new_array

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [25, 26, 27, 28],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [38]:
np.insert(new_array,2,np.array([1,2,3,4,5,6]),axis=1)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[ 5,  6,  1,  7,  8],
       [ 9, 10,  2, 11, 12],
       [25, 26,  3, 27, 28],
       [13, 14,  4, 15, 16],
       [17, 18,  5, 19, 20],
       [21, 22,  6, 23, 24]])

In [48]:
#NUMPY WITH PANDAS

In [49]:
df_stud_details=pd.DataFrame()

<IPython.core.display.Javascript object>

In [50]:
df_stud_details

Empty DataFrame
Columns: []
Index: []

In [52]:
sr_no=np.arange(1,101)

<IPython.core.display.Javascript object>

In [53]:
sr_no

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [54]:
name=np.random.choice(['A','B','C','D'],100)

<IPython.core.display.Javascript object>

In [55]:
name

array(['D', 'A', 'C', 'A', 'D', 'C', 'C', 'D', 'B', 'A', 'B', 'B', 'D',
       'A', 'A', 'B', 'A', 'D', 'D', 'C', 'C', 'A', 'C', 'B', 'B', 'A',
       'A', 'B', 'B', 'D', 'A', 'A', 'C', 'D', 'A', 'A', 'B', 'A', 'D',
       'D', 'D', 'A', 'D', 'A', 'A', 'D', 'D', 'C', 'D', 'A', 'C', 'A',
       'C', 'A', 'D', 'A', 'C', 'D', 'A', 'B', 'C', 'A', 'B', 'D', 'C',
       'A', 'D', 'A', 'D', 'A', 'B', 'A', 'A', 'B', 'D', 'D', 'C', 'B',
       'D', 'C', 'A', 'B', 'D', 'D', 'B', 'D', 'C', 'A', 'C', 'D', 'C',
       'C', 'D', 'B', 'B', 'B', 'B', 'B', 'C', 'A'], dtype='<U1')

In [56]:
gender=np.random.choice(['M','F','O'],100)

<IPython.core.display.Javascript object>

In [57]:
gender

array(['F', 'O', 'F', 'O', 'O', 'M', 'M', 'F', 'M', 'F', 'F', 'F', 'F',
       'M', 'M', 'O', 'O', 'O', 'O', 'O', 'M', 'M', 'F', 'O', 'O', 'O',
       'F', 'F', 'M', 'M', 'O', 'O', 'M', 'O', 'O', 'O', 'M', 'F', 'O',
       'F', 'O', 'F', 'F', 'F', 'O', 'M', 'O', 'O', 'O', 'M', 'O', 'F',
       'O', 'F', 'O', 'F', 'O', 'F', 'O', 'M', 'O', 'O', 'M', 'M', 'O',
       'F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'O', 'F', 'M', 'O', 'M',
       'O', 'F', 'O', 'M', 'M', 'M', 'O', 'F', 'M', 'O', 'O', 'M', 'O',
       'O', 'F', 'M', 'M', 'O', 'M', 'M', 'F', 'F'], dtype='<U1')

In [62]:
mark=np.random.randint(1,101,100)

<IPython.core.display.Javascript object>

In [63]:
mark

array([ 76,  73,  74,  25,  89,   8,   7,  26,   3,  20,  43,  30,   8,
        25,   9,  33,  93,  25,  66,  69,  16,   1,  11,   8,  99,  32,
        63,  64,   2,  18,  50,  19,  89,  83,  61,  80,  75,  26,  38,
        89,  80,  43,   6,  33,  37,  57,  28,  28,  57,  97,  40,  56,
        14,  69,  37,  71,  99,  70,  19, 100,   2,  14,  29,   3,  56,
        14,   3,  40,   5,  16,  82,   1,  68,  79,  13,  24,   8,  85,
        39,  82,  12,  59,  19,  15,  52,  49,  53,  76,  42,  60,  12,
        21,  58,  22,  25,  19,   7,  55,  75,   7])

In [64]:
df_stud_details['ID']=sr_no

In [65]:
df_stud_details['Name']=name

In [66]:
df_stud_details['Gender']=gender

In [67]:
df_stud_details['Marks']=mark

In [68]:
df_stud_details

ID Name Gender  Marks
0     1    D      F     76
1     2    A      O     73
2     3    C      F     74
3     4    A      O     25
4     5    D      O     89
..  ...  ...    ...    ...
95   96    B      O     19
96   97    B      M      7
97   98    B      M     55
98   99    C      F     75
99  100    A      F      7

[100 rows x 4 columns]

In [ ]:
find the sum of id column
find the missing values(if any)
find the no.of times 'D' name occuring in name column
find the average of Marks column
find the count of 'O' in gender column
find the duplicated rows