In [5]:
#insert
import numpy as np
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
c = np.insert(a,1, [[99, 88], [77, 66]], axis=0)
print(c)

[[[ 1  2]
  [ 3  4]]

 [[99 88]
  [77 66]]

 [[ 5  6]
  [ 7  8]]]


In [4]:
#append
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.append(a, [[7, 8, 9]], axis=0)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#delete
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d = np.delete(c, 1, axis=1)
print(d)

[[1 3]
 [4 6]
 [7 9]]
