<h2>Converts the array into 1D</h2>
<ul>
<li>
ravel - shallow copy
</li>
<li>
flatten - deep copy
</li>
</ul>


<li>np.append(old array,new array,axis=dimension-1)</li>

In [1]:
#Import package
import numpy as np

In [2]:
arr = np.arange(1,21).reshape(5,4)

In [5]:
arr1=np.ravel(arr)

In [4]:
arr.ndim

2

In [6]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [7]:
arr1.ndim

1

In [8]:
arr2 = arr.flatten()

In [9]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
arr2.ndim

1

In [24]:
arr = np.arange(1,101,2).reshape(5,5,2)
arr

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15],
        [17, 19]],

       [[21, 23],
        [25, 27],
        [29, 31],
        [33, 35],
        [37, 39]],

       [[41, 43],
        [45, 47],
        [49, 51],
        [53, 55],
        [57, 59]],

       [[61, 63],
        [65, 67],
        [69, 71],
        [73, 75],
        [77, 79]],

       [[81, 83],
        [85, 87],
        [89, 91],
        [93, 95],
        [97, 99]]])

In [25]:
arr.shape

(5, 5, 2)

In [29]:
temp_arr=np.arange(20,30).reshape(5,1,2)

In [30]:
upd_arr=np.append(arr,temp_arr,axis=2)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 1