<h1 style="color: red">Numpy Introduction</h1>
<ul style="color:#e3a412;">
    <li>Numpy is written in C language and it is bridged to python as C language is fast.</li>
    <h3 style="color: #e3a412">Functions</h3>
    <li>np.array(list_name)- converts the list to array</li>
    <li>np.arange(start, end) creates the numpy array from a given range</li>
    <li>np.zeros (a numpy consisting of zeroes)</li>
    <li>np.ones (a numpy consisting of zeroes)</li>
    <li>np.eye creates a eye view of an array</li>
    <li>np.random.randint this creates a numpy of random integers within a given range</li>
    <li>np.random.choice creates random numbers from existing numpy array</li>
    <li>np.linspace(start,stop,no.of elements required) It equally calculates the step size and return the required array</li>
    <li>sin,cos,tan</li>
    <li>sort,argsort</li>
    <li>max,min</li>
    <li>maximum,minimum</li>
    <li>sum</li>
    <li>mat</li>
    <li>linalg</li>
    <ol>
    <li>det</li>
    <li>inv</li>
    <li>eig</li>
    </ol>
    <li>argmax,argmin</li>
    <h3 style="color: red">Properties:</h3>
    <li>ndim - gets the number of dimension</li>
    <li>shape/reshape - gets/sets the size of each dimension</li>
</ul>

<p style="color: darkblue">As we all know there is a datatype in python called list where data can be stored irrespective of its datatype</p>
<br>
<p style="color: darkblue">Array is another data structure present in a package called numpy in python<br>
The array can consist only one datatype</p>


In [1]:
#A list is present below
lst = [45,78,1,2,69,49]
new_lst=[]
#For adding 1 in each of the list
for i in lst:
    new_lst+=[i+1]  

In [2]:
#Viewing the updated list
new_lst

[46, 79, 2, 3, 70, 50]

In [3]:
#Converting list into array
arr = np.array(lst)

<IPython.core.display.Javascript object>

In [4]:
#Viewing array before updating
arr

array([45, 78,  1,  2, 69, 49])

In [5]:
#Updating each element in the arrayy by 1
arr = arr+1

In [6]:
#Viewing array after updating
arr

array([46, 79,  2,  3, 70, 50])

In [7]:
#The arange function in numpy creates an array consisting of elements between the given range(step size is optional)
arr = np.arange(1,101,2)

<IPython.core.display.Javascript object>

In [8]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [9]:
#Zeros function creates an array consisting full of zeros in the given dimension
np.zeros((4,4),dtype='int')

<IPython.core.display.Javascript object>

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
#Ones function creates an array consisting full of zeros in the given dimension
np.ones((3,3))

<IPython.core.display.Javascript object>

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#Eye function creates an array of given dimensions filled with 0 and the third paramenter is the diagonal which is filled with ones
#below is an example of eye function
print(np.eye(4,5,-3))
print(np.eye(4,5,-2))
print(np.eye(4,5,-1))
print(np.eye(4,5,0))
print(np.eye(4,5,1))
print(np.eye(4,5,2))
print(np.eye(4,5,3))

<IPython.core.display.Javascript object>

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


<IPython.core.display.Javascript object>

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


<IPython.core.display.Javascript object>

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


<IPython.core.display.Javascript object>

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


<IPython.core.display.Javascript object>

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


<IPython.core.display.Javascript object>

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


<IPython.core.display.Javascript object>

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
#Random.randint creates an array with random numbers within a given range
#The end limit in not included
np.random.randint(1,50,10)

<IPython.core.display.Javascript object>

array([49, 20,  1, 20, 22,  6, 11, 39, 19, 34])

In [13]:
#Random.choice creates an array with random numbers with the reference of previous array
#Here the first parameter is the previous list and the next is no.of values required
np.random.choice(arr,10)

<IPython.core.display.Javascript object>

array([73, 69, 25, 15, 87, 83,  9,  1, 81, 71])

In [36]:
#Linspace creates an array with the given range and it is equally distributed for the given number of elements
np.linspace(1,2,10)

<IPython.core.display.Javascript object>

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [15]:
#Creating an array for the upcoming functions
arr=np.array([10,20,30,40,50,60,70,80,90,100])

<IPython.core.display.Javascript object>

In [16]:
#Sin 
np.sin(arr)

<IPython.core.display.Javascript object>

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485,
       -0.30481062,  0.77389068, -0.99388865,  0.89399666, -0.50636564])

In [17]:
#Cos
np.cos(arr)

<IPython.core.display.Javascript object>

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603,
       -0.95241298,  0.6333192 , -0.11038724, -0.44807362,  0.86231887])

In [18]:
#Tan
np.tan(arr)

<IPython.core.display.Javascript object>

array([ 0.64836083,  2.23716094, -6.4053312 , -1.11721493, -0.27190061,
        0.32004039,  1.22195992,  9.00365495, -1.99520041, -0.58721392])

<p>cross verifying sin/cos = tan with respective values from the above outputs<p>

In [19]:
#Answer is 0.64836083
-0.54402111/-0.83907153
#verified✅

0.648360825685505

In [20]:
#sort functions sorts the array elements in ascending order
np.sort(arr)

<IPython.core.display.Javascript object>

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [21]:
#Argsort returns the indices that would sort an array
np.argsort(arr)

<IPython.core.display.Javascript object>

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [22]:
#Max return the maximum value in the array
np.max(arr)

<IPython.core.display.Javascript object>

100

In [23]:
#Min return the minimum value in the array
np.min(arr)

<IPython.core.display.Javascript object>

10

In [24]:
#Maximum compares two arrays and returns the values highest in the format of an array
arr1 = np.array([10,45,78,96,25,26])
arr2 = np.array([13,58,74,56,20,100])
#Note: Both the arrays must have same number of elements
np.maximum(arr1,arr2)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([ 13,  58,  78,  96,  25, 100])

In [25]:
#Minimum compares two arrays and returns the values lowest in the format of an array
arr1 = np.array([10,45,78,96,25,26])
arr2 = np.array([13,58,74,56,20,100])
#Note: Both the arrays must have same number of elements
np.minimum(arr1,arr2)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([10, 45, 74, 56, 20, 26])

In [26]:
#Sum function adds up each element in the array
np.sum(arr)

<IPython.core.display.Javascript object>

550

In [27]:
#Mat in Numpy helps you to change the array to matrix
mat = np.mat(arr)
mat

<IPython.core.display.Javascript object>

matrix([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [28]:
#Linalg.det returns the determinant of the array
np.linalg.det(np.arange(1,10).reshape(3,3))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

6.66133814775094e-16

In [29]:
#Linalg.inv returns the Inverse of the array
np.linalg.inv(np.arange(1,10).reshape(3,3))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [30]:
#Argmax returns the index of max element in the array
np.argmax(arr)

<IPython.core.display.Javascript object>

9

In [31]:
#Argmin returns the index of min element in the array
np.argmin(arr)

<IPython.core.display.Javascript object>

0

In [32]:
#Eig gives the eigen values of the array
np.linalg.eig(np.arange(1,10).reshape(3,3))

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

(array([ 1.61168440e+01, -1.11684397e+00, -4.22209278e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [33]:
#ndim gives the dimension of the array
arr = np.arange(1,21).reshape(5,2,2)
arr.ndim

<IPython.core.display.Javascript object>

3

In [34]:
#Shape returns the no.of rows,columns in an array
arr.shape

(5, 2, 2)

In [35]:
#reshape using shape function
arr.shape=(5,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [50]:
#Creating an 2d array
arr = np.arange(1,21).reshape(5,4)

<IPython.core.display.Javascript object>

In [51]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [52]:
#Creating an new 2d array 
arr1 = np.array([[21,22,23,24]])

<IPython.core.display.Javascript object>

In [53]:
#Appending the new array to the existing array
res_arr = np.append(arr,arr1,axis=0)

<IPython.core.display.Javascript object>

In [40]:
#Successly appended the new array💯
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [54]:
#Viewing the Pre-Existing array
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [55]:
#Inserting in a array
np.insert(arr,5,[21,22,23,24],axis=0)

<IPython.core.display.Javascript object>

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [57]:
np.insert(arr,1,[21,22,23,24,25],axis=1)

<IPython.core.display.Javascript object>

array([[ 1, 21,  2,  3,  4],
       [ 5, 22,  6,  7,  8],
       [ 9, 23, 10, 11, 12],
       [13, 24, 14, 15, 16],
       [17, 25, 18, 19, 20]])

In [58]:
#Deleting in a array
np.delete(arr,1,axis=0)

<IPython.core.display.Javascript object>

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [59]:
np.delete(arr,3,axis=1)

<IPython.core.display.Javascript object>

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])