<h1>Numpy Introduction</h1>
<ul>
    <li>Numpy is written in C language and it is bridged to python as C language is fast.</li>
    <h3>Functions</h3>
    <li>np.array(list_name)- converts the list to array</li>
    <li>np.arange(start, end) creates the numpy array from a given range</li>
    <li>np.zeros (a numpy consisting of zeroes)</li>
    <li>np.ones (a numpy consisting of zeroes)</li>
    <li>np.eye creates a eye view of an array</li>
    <li>np.random.randint this creates a numpy of random integers within a given range</li>
    <li>np.random.choice creates random numbers from existing numpy array</li>
    <li>np.linspace(start,stop,no.of elements required) It equally calculates the step size and return the required array</li>
    <li>sin,cos,tan</li>
    <li>sort,argsort</li>
    <li>max,min</li>
    <li>maximum,minimum<li>
    <li>sum</li>
    <h5>mat</h5>
    <li>linalg</li>
    <li>det</li>
    <li>argmax,argmin</li>
    <li>inv</li>
    <li>eig</li>
    <h3>Properties:</h3>
    <li>ndim - gets the number of dimension</li>
    <li>shape/reshape - gets/sets the size of each dimension</li>
</ul>

Celcius to Farenheit
C*9/5+32=F

In [24]:
#list
lst = [45,78,1,2,69,49]
new_lst=[]
#suppose you want to perform an operation with each element(like adding 1 to each element)
for i in lst:
    new_lst+=[i+1]    

In [29]:
new_lst

[46, 79, 2, 3, 70, 50]

In [25]:
arr = np.array(lst)

In [26]:
arr

array([45, 78,  1,  2, 69, 49])

In [27]:
print(arr)

[45 78  1  2 69 49]


In [28]:
arr+1

array([46, 79,  2,  3, 70, 50])

In [30]:
arr = np.arange(1,101,2)

In [31]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [32]:
arr.shape

(50,)

In [37]:
arr = arr.reshape(5,10)

In [39]:
arr

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [42]:
arr.shape

(10, 5)

In [40]:
arr.shape=(10,5)

In [41]:
arr

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [50]:
arr = np.zeros((5,4),dtype='int')

In [51]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [68]:
arr = np.ones((5,4,4,4),dtype='int')

In [69]:
arr

array([[[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]],


       [[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]],


       [[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [

In [82]:
arr=np.eye(3,3,-2)

In [83]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [86]:
arr = np.random.randint(1,20,25)

In [87]:
arr

array([14, 18,  2, 15,  1, 18,  1, 18, 14, 18,  8, 14,  1,  8,  3,  6,  6,
       17, 16,  9, 15,  4,  6, 11, 16])

In [88]:
arr1 = np.random.choice(arr,10)

In [89]:
arr1

array([ 3, 16, 18,  6,  4, 16,  1, 14,  1,  2])

In [1]:
import numpy as np

In [2]:
#converting list to array
lst = [1,2,3,4,5,6,7,8,9]
arr = np.array(lst)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(arr)

numpy.ndarray

In [7]:
arr = np.arange(1,11).reshape(2,5)

In [8]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
arr.shape

(2, 5)

In [11]:
arr.ndim

2

In [14]:
arr = np.zeros((4,5),dtype="int")

In [15]:
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
arr.linspace

In [ ]:
arr = np.random.randint(start,stop,no.of values required)

In [ ]:
arr = np.random.choice(existing_arr,no.of values required)