In [1]:
arr=np.array([1,2,3,4,5])

<IPython.core.display.Javascript object>

In [5]:
arr1=np.arange(1,10,2)

<IPython.core.display.Javascript object>

In [6]:
arr1

array([1, 3, 5, 7, 9])

In [7]:
np.zeros((5,4))

<IPython.core.display.Javascript object>

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.eye(5,4,1)

<IPython.core.display.Javascript object>

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.random.randint(1,5,4)

<IPython.core.display.Javascript object>

array([4, 2, 1, 4])

In [12]:
np.random.choice(np.array([1,2,3,4]),10)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([1, 4, 2, 4, 2, 2, 2, 3, 2, 2])

In [13]:
np.linspace(1,10,5)

<IPython.core.display.Javascript object>

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [14]:
np.sin(arr)

<IPython.core.display.Javascript object>

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [15]:
np.cos(arr)

<IPython.core.display.Javascript object>

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [16]:
np.tan(arr)

<IPython.core.display.Javascript object>

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [17]:
arr.max()

5

In [18]:
arr

array([1, 2, 3, 4, 5])

In [19]:
arr.min()

1

In [20]:
arr.argmax()

4

In [21]:
arr.argmin()

0

In [22]:
arr1=np.array([1,2,3,4,5])

<IPython.core.display.Javascript object>

In [23]:
arr2=np.array([6,6,7,8,9])

<IPython.core.display.Javascript object>

In [24]:
np.maximum(arr1,arr2)

<IPython.core.display.Javascript object>

array([6, 6, 7, 8, 9])

In [25]:
np.minimum(arr1,arr2)

<IPython.core.display.Javascript object>

array([1, 2, 3, 4, 5])

In [26]:
np.sort(arr1)

<IPython.core.display.Javascript object>

array([1, 2, 3, 4, 5])

In [27]:
np.argsort(arr)

<IPython.core.display.Javascript object>

array([0, 1, 2, 3, 4], dtype=int64)

In [28]:
arr.sum()

15

In [29]:
arr2.sum()

36

In [36]:
matrix=np.matrix(arr.reshape(5,1))

<IPython.core.display.Javascript object>

In [37]:
matrix

matrix([[1],
        [2],
        [3],
        [4],
        [5]])

In [38]:
np.linalg.det(arr)

<IPython.core.display.Javascript object>

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [39]:
arr=np.arange(1,5).reshape(2,2)

<IPython.core.display.Javascript object>

In [40]:
arr

array([[1, 2],
       [3, 4]])

In [41]:
mat = np.matrix(arr)

<IPython.core.display.Javascript object>

In [42]:
np.linalg.det(mat)

<IPython.core.display.Javascript object>

-2.0000000000000004

In [44]:
np.linalg.inv(mat)

<IPython.core.display.Javascript object>

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [45]:
np.linalg.eig(mat)

<IPython.core.display.Javascript object>

(array([-0.37228132,  5.37228132]),
 matrix([[-0.82456484, -0.41597356],
         [ 0.56576746, -0.90937671]]))

In [46]:
arr.shape

(2, 2)

In [47]:
np.ndim(arr)

<IPython.core.display.Javascript object>

2

In [48]:
arr.ravel()

array([1, 2, 3, 4])

In [49]:
arr.flatten()

array([1, 2, 3, 4])

In [50]:
#ARRAY

In [61]:
#lets take a 4D array
a=np.random.randint(1,100,48).reshape(2,3,4,2)

<IPython.core.display.Javascript object>

In [62]:
a

array([[[[36, 68],
         [77, 89],
         [44, 24],
         [27, 15]],

        [[74, 16],
         [86, 79],
         [92, 12],
         [91, 26]],

        [[93, 15],
         [14, 10],
         [45, 68],
         [23, 70]]],


       [[[52, 22],
         [35, 17],
         [96, 80],
         [20, 54]],

        [[10, 29],
         [74, 77],
         [38, 87],
         [83, 12]],

        [[30, 51],
         [24, 26],
         [94, 14],
         [88,  7]]]])

In [63]:
b=np.random.randint(1,10,3*4*2).reshape(1,3,4,2)

<IPython.core.display.Javascript object>

In [64]:
b

array([[[[2, 5],
         [3, 9],
         [7, 1],
         [9, 1]],

        [[7, 7],
         [9, 5],
         [4, 3],
         [9, 7]],

        [[3, 5],
         [5, 3],
         [3, 2],
         [1, 5]]]])

In [65]:
a=np.append(a,b,axis=0)

<IPython.core.display.Javascript object>

In [66]:
a

array([[[[36, 68],
         [77, 89],
         [44, 24],
         [27, 15]],

        [[74, 16],
         [86, 79],
         [92, 12],
         [91, 26]],

        [[93, 15],
         [14, 10],
         [45, 68],
         [23, 70]]],


       [[[52, 22],
         [35, 17],
         [96, 80],
         [20, 54]],

        [[10, 29],
         [74, 77],
         [38, 87],
         [83, 12]],

        [[30, 51],
         [24, 26],
         [94, 14],
         [88,  7]]],


       [[[ 2,  5],
         [ 3,  9],
         [ 7,  1],
         [ 9,  1]],

        [[ 7,  7],
         [ 9,  5],
         [ 4,  3],
         [ 9,  7]],

        [[ 3,  5],
         [ 5,  3],
         [ 3,  2],
         [ 1,  5]]]])

In [67]:
#append into 2nd dimentsion
b=np.random.randint(1,10,3*4*2).reshape(3,1,4,2)
a=np.append(a,b,axis=1)
#now the shape becomes 3,4,4,2

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [68]:
#append into 3rd dimentsion
b=np.random.randint(1,10,3*4*2).reshape(3,4,1,2)
a=np.append(a,b,axis=2)
#now the shape becomes 3,4,5,2

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [69]:
#append into 4th dimentsion
b=np.random.randint(1,10,3*4*5).reshape(3,4,5,1)
a=np.append(a,b,axis=3)
#now the shape becomes 3,4,5,3

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>